### ISSUE TITLE
0.6.2 install fails

### ISSUE THREAD

**Issue by lgbaldoni** [hongquan/CoBang#25]
Packaging CoBang for openSUSE linux, this is what I see after the last update:
```
+ /usr/bin/meson install -C noarch-suse-linux --no-rebuild
Relocate to /home/abuild/rpmbuild/BUILD/CoBang-0.6.2
running install
running build
running build_py
running compile_catalog
error: invalid command 'compile_catalog'
```

**Comment by hongquan** [comment]
Hi @lgbaldoni, could you modify openSUSE build script, so that it install [`Babel`](https://pypi.org/project/Babel/) before building?

Currently, meson doesn't work because I haven't figured out why it doesn't see .*po files ([issue](https://github.com/hongquan/CoBang/issues/23#issuecomment-748020947)), so you should build it with _setup.py_.

But that is not all of headache. Recently, there is a [breaking change](https://github.com/pypa/setuptools/issues/1916) in `pip`, making Debian packaging tool fail, so I have to temporary exclude the step of install dependencies from _setup.py_ file.

**Comment by lgbaldoni** [comment]
> Hi @lgbaldoni, could you modify openSUSE build script, so that it install Babel before building?

That worked. Or at least the python bits were installed.

> Currently, meson doesn't work because I haven't figured out why it doesn't see .*po files (issue), so you should build it with setup.py.

The .po files are indeed not processed. Will also have a look.

**Comment by hongquan** [comment]
Got rid of _setup.py_ in favor of Meson.
