### ISSUE TITLE
[Question]: egg-info folder no longer installed

### ISSUE THREAD

**Issue by lgbaldoni** [hongquan/CoBang#29]
Do you think that could possibly be a problem?

**Comment by hongquan** [comment]
@lgbaldoni Yes, it is because I switched from _setup.py_ to Meson to build and Meson doesn't generate those info. I asked Meson author and got confirmed.

I switch to Meson because:
- `pip` recently has a breaking change, making _setup.py_ failed when building Debian package.
- The translation folder layout which is supported by _setup.py_ is not understood by Meson.

**Comment by hongquan** [comment]
Many GUI Python apps which are built with Meson also lack _egg-info_ and seem not to have big problem.

**Comment by hongquan** [comment]
Side note, _egg-info_ is [deprecated](https://packaging.python.org/discussions/wheel-vs-egg/) by _dist-info_ as a place to store metadata about installed packages. Unfortunately, both are not generated by Meson. However, there is a [spec](https://packaging.python.org/specifications/recording-installed-packages/) about _dist-info_ that we can base to make a Meson plugin to generate it.

In the wild, there is already a tool, PyO3's [maturin](https://github.com/PyO3/maturin), which can generate this directory.
