### ISSUE TITLE
[Question] Does it work on X11?

### ISSUE THREAD

**Issue by pizzadude** [hongquan/CoBang#8]
Does this app work on X11 DE's, like KDE Plasma 5?

Or do I have to use wayland?

**Comment by hongquan** [comment]
@pizzadude I tested with Kubuntu in VirtualBox and it can render the GUI properly. Haven't tested with webcam because by some reason, my webcam cannot be shared to VM (the webcam doesn't appear in the list of "can-be-shared").
Other DE, like Xfce, LxQt, the GUI cannot be rendered, but I'm suspecting it is VirtualBox issue, not DE.
I may need to install those OS on real machine to test again.

**Comment by pizzadude** [comment]
Ok. Thanks for replying. Looking forward to flathub release, because I don't use Ubuntu.

**Comment by hongquan** [comment]
Just tested with Kubuntu again, after fixing "device-sharing" with VirtualBox. The webcam doesn't work, due to other bug (my lack of testing on non-OpenGL environment). Will fix and test again.

The FlatHub submission is on progress. Based on some issues found out when testing with Flatpak, it seems that I will have to disable one feature for the app running from Flatpak.

**Comment by hongquan** [comment]
I finished testing on Kubuntu, Xubuntu, Lubuntu. All work with CoBang.

**Comment by pizzadude** [comment]
Flatpak version confirmed working in Fedora 32 KDE. Thanks!
